### ISSUE TITLE
Falsche Namen

### ISSUE THREAD

**Issue by gronon** [julien-klaus/KorrelationsAnalyse#3]
Medien: Zeile 7492, lobbyist.csv, Medien
Staats: Zeile 5718, lobbyist.csv, Manfred Staats
Hans: Zeile 12354, lobbyist.csv, Hans
a. : Extrahiert er bei Albert A. Gerllich das A. als eigenständigen Namen?
Martin Schulz: es gibt drei verschiedene in lobbyist.csv -> auch Martin Plagge
                     -> Alle mehrfach vorkommenden Namen werden auch mehrfach ausgegeben
Name: Zeile 1, lobbyist.csv
Peter Hahn != Peter Hahne ?

**Comment by julien-klaus** [comment]
Ich denke das hat mir dem Vergleich zu tun. Ich schaue mal rein.

**Comment by julien-klaus** [comment]
Es gibt nun wortgrenzen und somit werden zu lange wie Hahne nicht mehr gefunden
